#!/usr/bin/env sh

set -ex

while read -r docker_version compose_version;
do
  image=${DOCKER_REPO}:${docker_version}
  echo "# Building image ${image}..."

  docker build \
    --build-arg DOCKER_VERSION="${docker_version}" \
    --build-arg COMPOSE_VERSION="${compose_version}" \
    --pull \
    -t "${image}" .
done < DOCKER_AND_COMPOSE_VERSION_MATRIX
