#!/usr/bin/env sh

set -e

while read -r docker_version compose_version;
do
  if [ -z "${compose_version}" ]
  then
    tag="latest"
  else
    tag="${compose_version%.*}"
  fi
  image=${DOCKER_REPO}:${tag}

  echo "# Building image ${image}..."

  docker build \
    --build-arg DOCKER_VERSION="${docker_version}" \
    --build-arg COMPOSE_VERSION="${compose_version}" \
    --pull \
    -t "${image}" .
done < DOCKER_AND_COMPOSE_VERSION_MATRIX
