#!/usr/bin/env sh

set -e

images=$(docker image ls "${DOCKER_REPO}" --format "{{.Repository}}:{{.Tag}}");

for image in ${images};
do
  echo "# Pushing image ${image}..."
  docker image push "${image}"
  echo "Exit code: $?"
done
