#!/usr/bin/env sh

set -e

while read -r docker_version compose_version;
do
  image=${DOCKER_REPO}:${docker_version}
  echo "# Testing image ${image}..."
  export IMAGE_NAME=${image};

  docker-compose -f docker-compose.test.yml run --rm sut
done < DOCKER_AND_COMPOSE_VERSION_MATRIX
