#!/usr/bin/env sh

set -e

while read -r docker_version compose_version;
do
  if [ -z "${compose_version}" ]
  then
    tag="latest"
  else
    tag="${compose_version%.*}"
  fi
  image=${DOCKER_REPO}:${tag}

  echo "# Testing image ${image}..."
  export IMAGE_NAME="${image}"

  container=$(docker-compose -f docker-compose.test.yml run -d sut)

  if [ "$(docker container wait "${container}")" != "0" ]
  then
    echo "Test of ${IMAGE_NAME} failed"
    exit 1
  fi
  docker-compose -f docker-compose.test.yml rm --force sut
done < DOCKER_AND_COMPOSE_VERSION_MATRIX
